apiVersion: batch/v1
kind: Job
metadata:
  name: job-3
spec:
  completions: 3
  parallelism: 5
  backoffLimit: 4
  activeDeadlineSeconds: 3600
  template:
    spec:
      containers:
        - name: pi
          image: perl:5.34.0
          command: ["perl", "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
