apiVersion: v1
kind: Pod
metadata:
  labels:
    app: logger
    tier: backend
  name: logger
spec:
  containers:
    - name: logger
      image: dangodajango/logger:1.0.1
      imagePullPolicy: Always
      args: [ "ltf=true", "plf=/tmp/timestamp.log" ]
      volumeMounts:
        - mountPath: /tmp
          name: logs
  restartPolicy: OnFailure
  terminationGracePeriodSeconds: 30
  volumes:
    - name: logs
      emptyDir: { }